name: gestiondedepance
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  expense_repository:
    path: packages/expense_repository
  firebase_core: ^3.10.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  path_provider: ^2.1.5
  pdf: ^3.11.2
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  printing: ^5.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
