name: gestiondedepance
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.70.2
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  expense_repository:
    path: packages/expense_repository
  firebase_core: ^3.10.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  path_provider: ^2.1.5
  pdf: ^3.11.2
  permission_handler: ^11.3.1
  share_plus: ^10.1.4
  printing: ^5.14.0
  flutter_gemini: ^3.0.0
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
