name: expense_repository
description: the Repo for handling expenses

publish_to: "none"
version: 0.0.1

dependencies:
  cloud_firestore: ^5.6.2
  flutter_lints: ^5.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

flutter:
  uses-material-design: true
